

-- Generated by Relational Schema Center on Wed May 21 12:54:48 MSD 2008 for Informix Dynamic Server, V9.4

   
CREATE DATABASE july;

CREATE SCHEMA AUTHORIZATION informix;

CREATE TABLE informix.sequences
  (id CHAR(50) NOT NULL,
   value INTEGER NOT NULL);

ALTER TABLE informix.sequences ADD CONSTRAINT
  (PRIMARY KEY (id) CONSTRAINT pk_sequences);